---
# cPanel Git Deployment Configuration
# SUNDARI TOP STAR E-Commerce

deployment:
  tasks:
    - export DEPLOYPATH=/home/piesemas/public_html
    - /bin/cp -r * $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/config/config.php
    - /bin/chmod 644 $DEPLOYPATH/config/database.php
    - /bin/chmod 755 $DEPLOYPATH/assets/images/products
    - /bin/chmod -R 755 $DEPLOYPATH/admin
    - /bin/chmod -R 755 $DEPLOYPATH/api
    - /bin/chmod -R 755 $DEPLOYPATH/includes
    - /bin/chmod -R 755 $DEPLOYPATH/pages
