---
deployment:
  enabled: true
  development: false
  git:
    url: https://github.com/iwanro/masinicusut.git
    branch: main
  branches:
    main:
      source: https://github.com/iwanro/masinicusut.git
      reference: refs/heads/main
    exclude:
      - .gitignore
      - .cpanel.yml
      - debug_cart.php
      - IMPLEMENTATION_COMPLETE.md
      - CART_VERIFICATION.md
      - PRODUCT_IMAGES_GUIDE.md
      - logs/
      *.tmp
      *.log
      - .git/
      - .gitignore
  git_username: iwanro
    password: # Set in cPanel or use SSH key authentication
  deploy_path: ~/www/piesemasinicusut.ro
  environment:
    php: 7.4
    node: 18
    python: 3.11
    ruby: 3.3
    mysql: 5.7
    postgresql: 14
- name: "Production"
  composer: yes
    npm: yes
